name: dart_serialise
description: Dart serialisation tests
dependencies:
  browser: ^0.10.0
  js: ^0.6.0
  dson: ^0.3.4
  reflectable: ^0.5.4

transformers:
- reflectable:
    entry_points:
    - web/dson.dart
    - web/dson_bench.dart
